[package]
name = "springfield-meltdown"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.9"

[profile.dev]
opt-level = 1  # Faster debug builds while learning

[profile.release]
lto = true
codegen-units = 1
